language: python
python:
  - 3.7.x
#sudo: false
#before_deploy:
#  - openssl aes-256-cbc -K $encrypted_4a269b4e0d14_key -iv $encrypted_4a269b4e0d14_iv
#    -in deploy_rsa.enc -out deploy_rsa -d
#  - eval $(ssh-agent)
#  - chmod 600 deploy_rsa
#  - ssh-add deploy_rsa
#deploy:
#  provider: script
#  skip_cleanup: true
#  script: 'ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -p22 artbakulev@cinsear.ru
#  "cd ~/Alcohall/backend &&
#  git pull origin $TRAVIS_BRANCH &&
#  make api"'
#  on:
#    repo: $TRAVIS_REPO_SLUG
#    branch: dev