language: python
python:
  - 3.7.x
sudo: false
before_install:
  - openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv
    -in deploy_rsa.enc -out deploy_rsa -d
    - eval $(ssh-agent)
    - chmod 600 deploy_rsa
    - ssh-add deploy_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: 'ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -p22 root@104.248.83.114
  "cd ~/alcohall/backend &&
  git pull origin $TRAVIS_BRANCH &&
  scripts/run_api.sh"'
  on:
    branch: dev