# Generated by Django 3.0.4 on 2020-05-24 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cocktail", "0003_auto_20200509_1329"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Like",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="Активный?"),
                ),
                (
                    "cocktail",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cocktail.Cocktail",
                        verbose_name="Коктейль",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={"verbose_name": "Лайк", "verbose_name_plural": "Лайки",},
        ),
        migrations.AddField(
            model_name="user",
            name="likes",
            field=models.ManyToManyField(
                through="core.Like",
                to="cocktail.Cocktail",
                verbose_name="Лайки пользователя",
            ),
        ),
    ]
